### ISSUE TITLE
Screen is becoming black while I use snipping

### ISSUE THREAD

**Issue by Ankan1998** [keplerlab/enhant#2]
I am facing issue with screen going black while I am using snipping. 
I was using ad blocks. But I disabled ad block but still the issue persists for me. [adblock - adguard]
Chrome Version 91.0.4472.77

https://user-images.githubusercontent.com/36896102/121144627-ca819080-c85b-11eb-8c30-b97d14c32d9f.mp4

I have tried on two different site on medium blog and hugging face.
Links 
Hugging Face  - https://huggingface.co/
medium - https://medium.com/illuin/cleaning-up-dirty-scanned-documents-with-deep-learning-2e8e6de6cfa6

I am attaching some screenshot

![Screenshot (448)](https://user-images.githubusercontent.com/36896102/121140508-8ab8aa00-c857-11eb-94c4-4d00e96e76ed.png)

![Screenshot (449)](https://user-images.githubusercontent.com/36896102/121140454-7ecce800-c857-11eb-98da-5fcf6f72a901.png)

![Screenshot (454)](https://user-images.githubusercontent.com/36896102/121140539-94daa880-c857-11eb-83d1-bf0938d13585.png)

**Comment by thealokkr** [comment]
We upgraded it recently. Closing the issue for now
